"""Initial migration.

Revision ID: 0e30e4d5e8bd
Revises: 
Create Date: 2022-12-09 00:20:31.318454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e30e4d5e8bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files_data', schema=None) as batch_op:
        batch_op.drop_column('upload_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DATE(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
