"""Added a field for upload date

Revision ID: 5ed7bde3811d
Revises: 0e30e4d5e8bd
Create Date: 2022-12-09 00:21:28.733798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed7bde3811d'
down_revision = '0e30e4d5e8bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files_data', schema=None) as batch_op:
        batch_op.drop_column('upload_date')

    # ### end Alembic commands ###
