"""changed the upload_date datatype t String

Revision ID: efbbe71b8bb0
Revises: 5ed7bde3811d
Create Date: 2022-12-09 00:54:09.010626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efbbe71b8bb0'
down_revision = '5ed7bde3811d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files_data', schema=None) as batch_op:
        batch_op.alter_column('upload_date',
                              existing_type=sa.DATE(),
                              type_=sa.String(),
                              existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files_data', schema=None) as batch_op:
        batch_op.alter_column('upload_date',
                              existing_type=sa.String(),
                              type_=sa.DATE(),
                              existing_nullable=False)

    # ### end Alembic commands ###
